<?php

if( function_exists('acf_add_local_field_group') ) {

acf_add_local_field_group(array(
	'key' => 'group_dental_practice_fields',
	'title' => 'Dental Practice Information',
	'fields' => array(
		array(
			'key' => 'field_dental_services',
			'label' => 'Services Offered',
			'name' => 'services_offered',
			'type' => 'repeater',
			'instructions' => 'Add and manage dental services offered by your practice',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Service',
			'sub_fields' => array(
				array(
					'key' => 'field_service_name',
					'label' => 'Service Name',
					'name' => 'service_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_service_category',
					'label' => 'Category',
					'name' => 'service_category',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'general' => 'General',
						'cosmetic' => 'Cosmetic',
						'orthodontic' => 'Orthodontic',
						'surgical' => 'Surgical',
						'pediatric' => 'Pediatric',
					),
					'default_value' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'return_format' => 'value',
					'ajax' => 0,
				),
				array(
					'key' => 'field_service_description',
					'label' => 'Description',
					'name' => 'service_description',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 2,
				),
				array(
					'key' => 'field_service_duration',
					'label' => 'Typical Duration',
					'name' => 'service_duration',
					'type' => 'text',
					'instructions' => 'e.g., 30-45 minutes',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_service_price_range',
					'label' => 'Price Range',
					'name' => 'service_price_range',
					'type' => 'text',
					'instructions' => 'e.g., $100-$300',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_service_before_after',
					'label' => 'Before/After Images',
					'name' => 'service_before_after_images',
					'type' => 'gallery',
					'instructions' => 'Upload before and after images for this service',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'insert' => 'append',
					'library' => 'all',
					'min' => '',
					'max' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array(
			'key' => 'field_dental_staff',
			'label' => 'Dentist & Staff Profiles',
			'name' => 'staff_profiles',
			'type' => 'repeater',
			'instructions' => 'Add team members and their information',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Staff Member',
			'sub_fields' => array(
				array(
					'key' => 'field_staff_name',
					'label' => 'Name',
					'name' => 'staff_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_staff_title',
					'label' => 'Title/Position',
					'name' => 'staff_title',
					'type' => 'text',
					'instructions' => 'e.g., DDS, RDH, Office Manager',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '12',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_staff_photo',
					'label' => 'Photo',
					'name' => 'staff_photo',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '10',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_staff_credentials',
					'label' => 'Credentials/Degrees',
					'name' => 'staff_credentials',
					'type' => 'text',
					'instructions' => 'e.g., DDS, University of Pennsylvania',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '18',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_staff_specializations',
					'label' => 'Specializations',
					'name' => 'staff_specializations',
					'type' => 'text',
					'instructions' => 'e.g., Cosmetic, Orthodontics',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '18',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_staff_experience',
					'label' => 'Years of Experience',
					'name' => 'staff_experience',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '10',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'max' => '',
					'step' => 1,
				),
				array(
					'key' => 'field_staff_bio',
					'label' => 'Biography',
					'name' => 'staff_bio',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
				),
				array(
					'key' => 'field_staff_fun_fact',
					'label' => 'Fun Fact',
					'name' => 'staff_fun_fact',
					'type' => 'text',
					'instructions' => 'Share something personal about this team member',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_dental_insurance',
			'label' => 'Insurance Accepted',
			'name' => 'insurance_accepted',
			'type' => 'repeater',
			'instructions' => 'List insurance providers your practice accepts',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Insurance Provider',
			'sub_fields' => array(
				array(
					'key' => 'field_insurance_provider',
					'label' => 'Provider Name',
					'name' => 'insurance_provider_name',
					'type' => 'text',
					'instructions' => 'e.g., Delta Dental, United Healthcare',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_insurance_plans',
					'label' => 'Plan Types Accepted',
					'name' => 'insurance_plan_types',
					'type' => 'text',
					'instructions' => 'e.g., HMO, PPO, Indemnity',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '35',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_insurance_network',
					'label' => 'Network Status',
					'name' => 'insurance_network_status',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'in-network' => 'In-Network',
						'out-of-network' => 'Out-of-Network',
					),
					'default_value' => 'in-network',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'return_format' => 'value',
					'ajax' => 0,
				),
			),
		),
		array(
			'key' => 'field_dental_amenities',
			'label' => 'Patient Amenities',
			'name' => 'patient_amenities',
			'type' => 'repeater',
			'instructions' => 'List special amenities available to patients',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Amenity',
			'sub_fields' => array(
				array(
					'key' => 'field_amenity_name',
					'label' => 'Amenity Name',
					'name' => 'amenity_name',
					'type' => 'text',
					'instructions' => 'e.g., WiFi, Massage Chairs, Refreshments',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_amenity_description',
					'label' => 'Description',
					'name' => 'amenity_description',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 2,
				),
				array(
					'key' => 'field_amenity_icon',
					'label' => 'Icon',
					'name' => 'amenity_icon',
					'type' => 'image',
					'instructions' => 'Upload an icon for this amenity',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',