<?php

acf_import_field_group(array(
	'key' => 'group_dental_practice_fields',
	'title' => 'Dental Practice Fields',
	'fields' => array(
		array(
			'key' => 'field_services_offered',
			'label' => 'Services Offered',
			'name' => 'services_offered',
			'type' => 'repeater',
			'button_label' => 'Add Service',
			'sub_fields' => array(
				array(
					'key' => 'field_service_name',
					'label' => 'Service Name',
					'name' => 'service_name',
					'type' => 'text',
					'required' => 1,
				),
				array(
					'key' => 'field_service_category',
					'label' => 'Category',
					'name' => 'service_category',
					'type' => 'select',
					'choices' => array(
						'general' => 'General',
						'cosmetic' => 'Cosmetic',
						'orthodontic' => 'Orthodontic',
						'surgical' => 'Surgical',
						'pediatric' => 'Pediatric',
					),
					'required' => 1,
				),
				array(
					'key' => 'field_service_description',
					'label' => 'Description',
					'name' => 'service_description',
					'type' => 'textarea',
				),
				array(
					'key' => 'field_service_duration',
					'label' => 'Typical Duration',
					'name' => 'service_duration',
					'type' => 'text',
					'placeholder' => 'e.g., 30-45 minutes',
				),
				array(
					'key' => 'field_service_price_range',
					'label' => 'Price Range',
					'name' => 'service_price_range',
					'type' => 'text',
					'placeholder' => 'e.g., $200 - $400',
				),
				array(
					'key' => 'field_service_before_after',
					'label' => 'Before/After Images',
					'name' => 'service_before_after',
					'type' => 'gallery',
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_staff_profiles',
			'label' => 'Dentist & Staff Profiles',
			'name' => 'staff_profiles',
			'type' => 'repeater',
			'button_label' => 'Add Staff Member',
			'sub_fields' => array(
				array(
					'key' => 'field_staff_name',
					'label' => 'Name',
					'name' => 'staff_name',
					'type' => 'text',
					'required' => 1,
				),
				array(
					'key' => 'field_staff_title',
					'label' => 'Title',
					'name' => 'staff_title',
					'type' => 'text',
					'placeholder' => 'e.g., General Dentist, Hygienist',
				),
				array(
					'key' => 'field_staff_photo',
					'label' => 'Photo',
					'name' => 'staff_photo',
					'type' => 'image',
					'return_format' => 'array',
				),
				array(
					'key' => 'field_staff_credentials',
					'label' => 'Credentials/Degrees',
					'name' => 'staff_credentials',
					'type' => 'textarea',
					'placeholder' => 'e.g., DDS, University of...',
				),
				array(
					'key' => 'field_staff_specializations',
					'label' => 'Specializations',
					'name' => 'staff_specializations',
					'type' => 'text',
				),
				array(
					'key' => 'field_staff_experience',
					'label' => 'Years of Experience',
					'name' => 'staff_experience',
					'type' => 'number',
				),
				array(
					'key' => 'field_staff_bio',
					'label' => 'Biography',
					'name' => 'staff_bio',
					'type' => 'textarea',
				),
				array(
					'key' => 'field_staff_fun_fact',
					'label' => 'Fun Fact',
					'name' => 'staff_fun_fact',
					'type' => 'text',
					'placeholder' => 'Something personal about the staff member',
				),
			),
		),
		array(
			'key' => 'field_insurance_accepted',
			'label' => 'Insurance Accepted',
			'name' => 'insurance_accepted',
			'type' => 'repeater',
			'button_label' => 'Add Insurance Provider',
			'sub_fields' => array(
				array(
					'key' => 'field_insurance_provider_name',
					'label' => 'Provider Name',
					'name' => 'insurance_provider_name',
					'type' => 'text',
					'required' => 1,
				),
				array(
					'key' => 'field_insurance_plan_types',
					'label' => 'Plan Types Accepted',
					'name' => 'insurance_plan_types',
					'type' => 'text',
					'placeholder' => 'e.g., PPO, HMO, Indemnity',
				),
				array(
					'key' => 'field_insurance_network_status',
					'label' => 'Network Status',
					'name' => 'insurance_network_status',
					'type' => 'select',
					'choices' => array(
						'in-network' => 'In-Network',
						'out-of-network' => 'Out-of-Network',
					),
				),
			),
		),
		array(
			'key' => 'field_patient_amenities',
			'label' => 'Patient Amenities',
			'name' => 'patient_amenities',
			'type' => 'repeater',
			'button_label' => 'Add Amenity',
			'sub_fields' => array(
				array(
					'key' => 'field_amenity_name',
					'label' => 'Amenity Name',
					'name' => 'amenity_name',
					'type' => 'text',
					'required' => 1,
				),
				array(
					'key' => 'field_amenity_description',
					'label' => 'Description',
					'name' => 'amenity_description',
					'type' => 'textarea',
				),
				array(
					'key' => 'field_amenity_icon',
					'label' => 'Icon',
					'name' => 'amenity_icon',
					'type' => 'image',
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_technology_equipment',
			'label' => 'Technology & Equipment',
			'name' => 'technology_equipment',
			'type' => 'repeater',
			'button_label' => 'Add Technology',
			'sub_fields' => array(
				array(
					'key' => 'field_tech_name',
					'label' => 'Technology Name',
					'name' => 'tech_name',
					'type' => 'text',
					'required' => 1,
				),
				array(
					'key' => 'field_tech_description',
					'label' => 'Description',
					'name' => 'tech_description',
					'type' => 'textarea',
				),
				array(
					'key' => 'field_tech_patient_benefit',
					'label' => 'Benefit to Patient',
					'name' => 'tech_patient_benefit',
					'type' => 'textarea',
				),
				array(
					'key' => 'field_tech_image',
					'label' => 'Image',
					'name' => 'tech_image',
					'type' => 'image',
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_office_hours',
			'label' => 'Office Hours',
			'name' => 'office_hours',
			'type' => 'repeater',
			'button_label' => 'Add Day',
			'sub_fields' => array(
				array(
					'key' => 'field_hours_day_name',
					'label' => 'Day Name',
					'name' => 'hours_day_name',
					'type' => 'select',
					'choices' => array(
						'monday' => 'Monday',
						'tuesday' => 'Tuesday',
						'wednesday' => 'Wednesday',
						'thursday' => 'Thursday',
						'friday' => 'Friday',
						'saturday' => 'Saturday',
						'sunday' => 'Sunday',
					),
					'required' => 1,
				),
				array(
					'key' => 'field_hours_open_time',
					'label' => 'Open Time',
					'name' => 'hours_open_time',
					'type' => 'time_picker',
				),
				array(
					'key' => 'field_hours_close_time',
					'label' => 'Close Time',
					'name' => 'hours_close_time',
					'type' => 'time_picker',
				),
				array(
					'key' => 'field_hours_is_closed',
					'label' => 'Closed',
					'name' => 'hours_is_closed',
					'type' => 'true_false',
				),
			),
		),
		array(
			'key' => 'field_emergency_same_day',
			'label' => 'Same-Day Emergency Appointments Available',
			'name' => 'emergency_same_day',
			'type' => 'true_false',
		),
		array(
			'key' => 'field_emergency_phone',
			'label' => 'Emergency Phone Number',
			'name' => 'emergency_phone',
			'type' => 'text',
		),
		array(
			'key' => 'field_emergency_instructions',
			'label' => 'After-Hours Instructions',
			'name' => 'emergency_instructions',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_new_patient_welcome',
			'label' => 'New Patient Welcome Message',
			'name' => 'new_patient_welcome',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_new_patient_forms_url',
			'label' => 'Patient Forms Download URL',
			'name' => 'new_patient_forms_url',
			'type' => 'url',
		),
		array(
			'key' => 'field_new_patient_bring',
			'label' => 'What to Bring',
			'name' => 'new_patient_bring',
			'type' => 'repeater',
			'button_label' => 'Add Item',
			'sub_fields' => array(
				array(
					'key' => 'field_bring_item',
					'label' => 'Item',
					'name' => 'bring_item',
					'type' => 'text',
					'required' => 1,
				),
			),
		),
		array(
			'key' => 'field_service_areas',
			'label' => 'Service Areas',
			'name' => 'service_areas',
			'type' => 'repeater',
			'button_label' => 'Add Service Area',
			'sub_fields' => array(
				array(
					'key' => 'field_area_city_name',
					'label' => 'City Name',
					'name' => 'area_city_name',
					'type' => 'text',
					'required' => 1,
				),
				array(
					'key' => 'field_area_distance',
					'label' => 'Distance from Office',
					'name' => 'area_distance',
					'type' => 'text',
					'placeholder' => 'e.g., 5 miles',
				),
				array(
					'key' => 'field_area_accepts_patients',
					'label' => 'Accepts New Patients',
					'name' => 'area_accepts_patients',
					'type' => 'true_false',
				),
			),
		),
		array(
			'key' => 'field_payment_options',
			'label' => 'Payment Options',
			'name' => 'payment_options',
			'type' => 'repeater',
			'button_label' => 'Add Payment Option',
			'sub_fields' => array(
				array(
					'key' => 'field_payment_option_name',
					'label' => 'Option Name',
					'name' => 'payment_option_name',
					'type' => 'text',
					'required' => 1,
				),
				array(
					'key' => 'field_payment_option_description',
					'label' => 'Description',
					'name' => 'payment_option_description',
					'type' => 'textarea',
				),
				array(
					'key' => 'field_payment_financing_available',
					'label' => 'Financing Available',
					'name' => 'payment_financing_available',
					'type' => 'true_false',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Complete field group for dental practice website information',
));

?>