<?php

if ( function_exists( 'acf_add_local_field_group' ) ) {
    acf_add_local_field_group( array(
        'key'                   => 'group_hvac_company_fields',
        'title'                 => 'HVAC Company Information',
        'fields'                => array(
            array(
                'key'           => 'field_hvac_services',
                'label'         => 'Company Services',
                'name'          => 'hvac_services',
                'type'          => 'repeater',
                'instructions'  => 'Add your HVAC services with descriptions and pricing',
                'required'      => 1,
                'collapsed'     => '',
                'min'           => 0,
                'max'           => 0,
                'layout'        => 'table',
                'button_label'  => 'Add Service',
                'sub_fields'    => array(
                    array(
                        'key'           => 'field_service_name',
                        'label'         => 'Service Name',
                        'name'          => 'service_name',
                        'type'          => 'text',
                        'instructions'  => 'e.g., Air Conditioning Repair',
                        'required'      => 1,
                    ),
                    array(
                        'key'           => 'field_service_description',
                        'label'         => 'Description',
                        'name'          => 'service_description',
                        'type'          => 'textarea',
                        'instructions'  => 'Detailed description of the service',
                        'required'      => 1,
                        'rows'          => 3,
                    ),
                    array(
                        'key'           => 'field_service_icon_class',
                        'label'         => 'Icon Class',
                        'name'          => 'service_icon_class',
                        'type'          => 'text',
                        'instructions'  => 'Font Awesome or custom icon class (e.g., fa-snowflake)',
                        'required'      => 0,
                    ),
                    array(
                        'key'           => 'field_service_price_range',
                        'label'         => 'Price Range',
                        'name'          => 'service_price_range',
                        'type'          => 'text',
                        'instructions'  => 'e.g., $150 - $500',
                        'required'      => 1,
                    ),
                ),
            ),
            array(
                'key'           => 'field_service_areas',
                'label'         => 'Service Areas',
                'name'          => 'service_areas',
                'type'          => 'repeater',
                'instructions'  => 'Define geographic service areas',
                'required'      => 1,
                'collapsed'     => '',
                'min'           => 0,
                'max'           => 0,
                'layout'        => 'table',
                'button_label'  => 'Add Service Area',
                'sub_fields'    => array(
                    array(
                        'key'           => 'field_area_city',
                        'label'         => 'City/Town Name',
                        'name'          => 'city_town_name',
                        'type'          => 'text',
                        'required'      => 1,
                    ),
                    array(
                        'key'           => 'field_area_zip_codes',
                        'label'         => 'Zip Codes Served',
                        'name'          => 'zip_codes_served',
                        'type'          => 'textarea',
                        'instructions'  => 'Enter zip codes, separated by commas',
                        'required'      => 0,
                        'rows'          => 3,
                    ),
                    array(
                        'key'           => 'field_area_radius',
                        'label'         => 'Service Radius (miles)',
                        'name'          => 'service_radius_miles',
                        'type'          => 'number',
                        'required'      => 0,
                        'min'           => 0,
                        'step'          => 0.5,
                    ),
                ),
            ),
            array(
                'key'           => 'field_team_members',
                'label'         => 'Team Members',
                'name'          => 'team_members',
                'type'          => 'repeater',
                'instructions'  => 'Add your HVAC technicians and staff',
                'required'      => 0,
                'collapsed'     => '',
                'min'           => 0,
                'max'           => 0,
                'layout'        => 'block',
                'button_label'  => 'Add Team Member',
                'sub_fields'    => array(
                    array(
                        'key'           => 'field_member_name',
                        'label'         => 'Name',
                        'name'          => 'member_name',
                        'type'          => 'text',
                        'required'      => 1,
                    ),
                    array(
                        'key'           => 'field_member_role',
                        'label'         => 'Role/Title',
                        'name'          => 'member_role',
                        'type'          => 'text',
                        'instructions'  => 'e.g., Senior Technician, Manager',
                        'required'      => 1,
                    ),
                    array(
                        'key'           => 'field_member_photo',
                        'label'         => 'Photo',
                        'name'          => 'member_photo',
                        'type'          => 'image',
                        'required'      => 0,
                        'return_format' => 'id',
                        'preview_size'  => 'thumbnail',
                    ),
                    array(
                        'key'           => 'field_member_certifications',
                        'label'         => 'Certifications',
                        'name'          => 'member_certifications',
                        'type'          => 'textarea',
                        'instructions'  => 'List certifications, separated by commas',
                        'required'      => 0,
                        'rows'          => 3,
                    ),
                    array(
                        'key'           => 'field_member_experience',
                        'label'         => 'Years of Experience',
                        'name'          => 'member_experience_years',
                        'type'          => 'number',
                        'required'      => 0,
                        'min'           => 0,
                        'step'          => 1,
                    ),
                    array(
                        'key'           => 'field_member_bio',
                        'label'         => 'Biography',
                        'name'          => 'member_bio',
                        'type'          => 'textarea',
                        'instructions'  => 'Short bio about the team member',
                        'required'      => 0,
                        'rows'          => 4,
                    ),
                ),
            ),
            array(
                'key'           => 'field_certifications_licenses',
                'label'         => 'Certifications & Licenses',
                'name'          => 'certifications_licenses',
                'type'          => 'repeater',
                'instructions'  => 'Add company certifications and licenses',
                'required'      => 0,
                'collapsed'     => '',
                'min'           => 0,
                'max'           => 0,
                'layout'        => 'table',
                'button_label'  => 'Add Certification',
                'sub_fields'    => array(
                    array(
                        'key'           => 'field_cert_name',
                        'label'         => 'Certification Name',
                        'name'          => 'cert_name',
                        'type'          => 'text',
                        'required'      => 1,
                    ),
                    array(
                        'key'           => 'field_cert_issuing_body',
                        'label'         => 'Issuing Body',
                        'name'          => 'cert_issuing_body',
                        'type'          => 'text',
                        'instructions'  => 'Organization that issued the certification',
                        'required'      => 1,
                    ),
                    array(
                        'key'           => 'field_cert_license_number',
                        'label'         => 'License Number',
                        'name'          => 'cert_license_number',
                        'type'          => 'text',
                        'required'      => 1,
                    ),
                    array(
                        'key'           => 'field_cert_expiration_date',
                        'label'         => 'Expiration Date',
                        'name'          => 'cert_expiration_date',
                        'type'          => 'date_picker',
                        'required'      => 0,
                        'display_format' => 'm/d/Y',
                        'return_format' => 'Y-m-d',
                    ),
                ),
            ),
            array(
                'key'           => 'field_business_hours',
                'label'         => 'Business Hours',
                'name'          => 'business_hours',
                'type'          => 'repeater',
                'instructions'  => 'Set operating hours for each day of the week',
                'required'      => 0,
                'collapsed'     => '',
                'min'           => 0,
                'max'           => 7,
                'layout'        => 'table',
                'button_label'  => 'Add Day',
                'sub_fields'    => array(
                    array(
                        'key'           => 'field_hours_day_name',
                        'label'         => 'Day of Week',
                        'name'          => 'day_name',
                        'type'          => 'select',
                        'choices'       => array(
                            'Monday'    => 'Monday',
                            'Tuesday'   => 'Tuesday',
                            'Wednesday' => 'Wednesday',
                            'Thursday'  => 'Thursday',
                            'Friday'    => 'Friday',
                            'Saturday'  => 'Saturday',
                            'Sunday'    => 'Sunday',
                        ),
                        'required'      => 1,
                    ),
                    array(
                        'key'           => 'field_hours_open_time',
                        'label'         => 'Open Time',
                        'name'          => 'open_time',
                        'type'          => 'time_picker',
                        'required'      => 0,
                        'display_format' => 'g:i a',
                        'return_format' => 'H:i',
                    ),
                    array(
                        'key'           => 'field_hours_close_time',
                        'label'         => 'Close Time',
                        'name'          => 'close_time',
                        'type'          => 'time_picker',
                        'required'      => 0,
                        'display_format' => 'g:i a',
                        'return_format' => 'H:i',
                    ),
                    array(
                        'key'           => 'field_hours_is_closed',
                        'label'         => 'Closed This Day',
                        'name'          => 'is_closed',
                        'type'          => 'true_false',
                        'instructions'  => 'Check if closed on this day',
                        'ui'            => 1,
                    ),
                ),
            ),
            array(
                'key'           => 'field_emergency_service',
                'label'         => 'Emergency Service Availability',
                'name'          => 'emergency_service_available',
                'type'          => 'true_false',
                'instructions'  => 'Do you offer emergency after-hours service?',
                'ui'            => 1,
            ),
            array(
                'key'           => 'field_emergency_phone',
                'label'         => 'After-Hours Emergency Phone Number',
                'name'          => 'emergency_phone_number',
                'type'          => 'text',
                'instructions'  => 'Phone number for emergency calls',
                'required'      => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field'     => 'field_emergency_service',
                            'operator'  => '==',
                            'value'     => '1',
                        ),
                    ),
                ),
            ),
            array(
                'key'           => 'field_response_time',
                'label'         => 'Response Time Guarantee',
                'name'          => 'response_time_guarantee',
                'type'          => 'text',
                'instructions'  => 'e.g., 1 hour, 4 hours, Same day',
                'required'      => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field'     => 'field_emergency_service',
                            'operator'  => '==',
                            'value'     => '1',
                        ),
                    ),
                ),
            ),
            array(
                'key'           => 'field_brands_serviced',
                'label'         => 'Brands Serviced',
                'name'          => 'brands_serviced',
                'type'          => 'repeater',
                'instructions'  => 'Add HVAC brands you service and maintain',
                'required'      => 0,
                'collapsed'     => '',
                'min'           => 0,
                'max'           => 0,
                'layout'        => 'block',
                'button_label'  => 'Add Brand',
                'sub_fields'    => array(
                    array(
                        'key'           => 'field_brand_name',
                        'label'         => 'Brand Name',
                        'name'          => 'brand_name',
                        'type'          => 'text',
                        'required'      => 1,
                    ),
                    array(
                        'key'           => 'field_brand_logo',
                        'label'         => 'Brand Logo',
                        'name'          => 'brand_logo',
                        'type'          => 'image',
                        'required'      => 0,
                        'return_format' => 'id',
                        'preview_size'  => 'thumbnail',
                    ),
                    array(
                        'key'           => 'field_authorized_dealer',
                        'label'         => 'Authorized Dealer',
                        'name'          => 'authorized_dealer',
                        'type'          => 'true_false',
                        'instructions'  => 'Is your company an authorized dealer for this brand?',
                        'ui'            => 1,
                    ),
                ),
            ),
            array(
                'key'           => 'field_financing_description',
                'label'         => 'Financing Options Description',
                'name'          => 'financing_description',
                'type'          => 'textarea',
                'instructions'  => 'General information about financing options available',
                'required'      => 0,
                'rows'          => 4,
            ),
            array(
                'key'           => 'field_financing_plans',
                'label'         => 'Financing Plans',
                'name'          => 'financing_plans',
                'type'          => 'repeater',
                'instructions'  => 'Add specific financing plan options',
                'required'      => 0,
                'collapsed'     => '',
                'min'           => 0,
                'max'           => 0,
                'layout'        => 'table',
                'button_label'  => 'Add Financing Plan',
                'sub_fields'    => array(
                    array(
                        'key'           => 'field_plan_name',
                        'label'         => 'Plan Name',
                        'name'          => 'plan_name',
                        'type'          => 'text',
                        'instructions'  => 'e.g., 12-Month No Interest',
                        'required'      => 1,
                    ),
                    array(
                        'key'           => 'field_plan_term_months',
                        'label'         => 'Term (Months)',
                        'name'          => 'plan_term_months',
                        'type'          => 'number',
                        'required'      => 1,
                        'min'           => 1,
                        'step'          => 1,
                    ),
                    array(
                        'key'           => 'field_plan_apr',
                        'label'         => 'APR (%)',
                        'name'          => 'plan_apr',
                        'type'          => 'number',
                        'required'      => 1,
                        'min'           => 0,
                        'max'           => 100,
                        'step'          => 0.01,
                    ),
                ),
            ),
        ),
        'location'          => array(
            array(
                array(
                    'param'     => 'post_type',
                    'operator'  => '==',
                    'value'     => 'page',
                ),
            ),
        ),
        'menu_order'        => 0,
        'position'          => 'normal',
        'style'             => 'default',
        'label_placement'   => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'    => '',
        'active'            => true,
        'description'       => 'HVAC Company information and services',
    ) );
}