<?php

if( function_exists('acf_import_field_group') ) {
    acf_import_field_group(array(
        'key' => 'group_legal_firm_fields',
        'title' => 'Law Firm Information',
        'fields' => array(
            array(
                'key' => 'field_practice_areas_section',
                'label' => 'Practice Areas',
                'name' => 'practice_areas_section',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_practice_areas',
                'label' => 'Practice Areas',
                'name' => 'practice_areas',
                'type' => 'repeater',
                'layout' => 'table',
                'button_label' => 'Add Practice Area',
                'sub_fields' => array(
                    array(
                        'key' => 'field_practice_area_name',
                        'label' => 'Area Name',
                        'name' => 'area_name',
                        'type' => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_practice_area_description',
                        'label' => 'Description',
                        'name' => 'description',
                        'type' => 'textarea',
                        'rows' => 4,
                    ),
                    array(
                        'key' => 'field_practice_area_icon',
                        'label' => 'Icon',
                        'name' => 'icon',
                        'type' => 'image',
                        'return_format' => 'array',
                    ),
                    array(
                        'key' => 'field_practice_area_primary',
                        'label' => 'Primary Practice Area',
                        'name' => 'is_primary',
                        'type' => 'true_false',
                        'ui' => 1,
                    ),
                ),
            ),
            array(
                'key' => 'field_attorneys_section',
                'label' => 'Attorneys',
                'name' => 'attorneys_section',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_attorneys',
                'label' => 'Attorney Profiles',
                'name' => 'attorneys',
                'type' => 'repeater',
                'layout' => 'block',
                'button_label' => 'Add Attorney',
                'sub_fields' => array(
                    array(
                        'key' => 'field_attorney_name',
                        'label' => 'Full Name',
                        'name' => 'name',
                        'type' => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_attorney_title',
                        'label' => 'Title/Position',
                        'name' => 'title',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_attorney_photo',
                        'label' => 'Photo',
                        'name' => 'photo',
                        'type' => 'image',
                        'return_format' => 'array',
                    ),
                    array(
                        'key' => 'field_attorney_bar_admissions',
                        'label' => 'Bar Admissions',
                        'name' => 'bar_admissions',
                        'type' => 'repeater',
                        'layout' => 'table',
                        'button_label' => 'Add Bar Admission',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_bar_state',
                                'label' => 'State/Jurisdiction',
                                'name' => 'state',
                                'type' => 'text',
                            ),
                            array(
                                'key' => 'field_bar_year',
                                'label' => 'Year Admitted',
                                'name' => 'year_admitted',
                                'type' => 'number',
                            ),
                            array(
                                'key' => 'field_bar_number',
                                'label' => 'Bar Number',
                                'name' => 'bar_number',
                                'type' => 'text',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_attorney_education',
                        'label' => 'Education',
                        'name' => 'education',
                        'type' => 'repeater',
                        'layout' => 'table',
                        'button_label' => 'Add Education',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_education_school',
                                'label' => 'School/University',
                                'name' => 'school',
                                'type' => 'text',
                            ),
                            array(
                                'key' => 'field_education_degree',
                                'label' => 'Degree',
                                'name' => 'degree',
                                'type' => 'text',
                            ),
                            array(
                                'key' => 'field_education_year',
                                'label' => 'Year Graduated',
                                'name' => 'year',
                                'type' => 'number',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_attorney_practice_focus',
                        'label' => 'Practice Focus Areas',
                        'name' => 'practice_focus',
                        'type' => 'relationship',
                        'post_type' => array( 0 => 'post' ),
                        'taxonomy' => '',
                        'filters' => array( 0 => 'search' ),
                        'elements' => '',
                        'min' => '',
                        'max' => '',
                        'return_format' => 'object',
                    ),
                    array(
                        'key' => 'field_attorney_bio',
                        'label' => 'Biography',
                        'name' => 'bio',
                        'type' => 'wysiwyg',
                        'toolbar' => 'full',
                    ),
                    array(
                        'key' => 'field_attorney_email',
                        'label' => 'Email',
                        'name' => 'email',
                        'type' => 'email',
                    ),
                    array(
                        'key' => 'field_attorney_phone',
                        'label' => 'Phone',
                        'name' => 'phone',
                        'type' => 'text',
                    ),
                ),
            ),
            array(
                'key' => 'field_offices_section',
                'label' => 'Office Locations',
                'name' => 'offices_section',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_office_locations',
                'label' => 'Office Locations',
                'name' => 'office_locations',
                'type' => 'repeater',
                'layout' => 'block',
                'button_label' => 'Add Office',
                'sub_fields' => array(
                    array(
                        'key' => 'field_office_name',
                        'label' => 'Office Name',
                        'name' => 'office_name',
                        'type' => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_office_address',
                        'label' => 'Street Address',
                        'name' => 'address',
                        'type' => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_office_city',
                        'label' => 'City',
                        'name' => 'city',
                        'type' => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_office_state',
                        'label' => 'State',
                        'name' => 'state',
                        'type' => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_office_zip',
                        'label' => 'ZIP Code',
                        'name' => 'zip',
                        'type' => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_office_phone',
                        'label' => 'Phone',
                        'name' => 'phone',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_office_fax',
                        'label' => 'Fax',
                        'name' => 'fax',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_office_coordinates',
                        'label' => 'Map Coordinates',
                        'name' => 'map_coordinates',
                        'type' => 'google_map',
                        'center_lat' => '40.7128',
                        'center_lng' => '-74.0060',
                        'zoom' => 13,
                        'height' => '400',
                    ),
                    array(
                        'key' => 'field_office_parking',
                        'label' => 'Parking Information',
                        'name' => 'parking_info',
                        'type' => 'textarea',
                        'rows' => 3,
                    ),
                ),
            ),
            array(
                'key' => 'field_case_results_section',
                'label' => 'Case Results & Testimonials',
                'name' => 'case_results_section',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_case_results',
                'label' => 'Case Results & Testimonials',
                'name' => 'case_results',
                'type' => 'repeater',
                'layout' => 'block',
                'button_label' => 'Add Case Result',
                'sub_fields' => array(
                    array(
                        'key' => 'field_case_type',
                        'label' => 'Case Type',
                        'name' => 'case_type',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_case_result_summary',
                        'label' => 'Result Summary',
                        'name' => 'result_summary',
                        'type' => 'textarea',
                        'rows' => 4,
                    ),
                    array(
                        'key' => 'field_client_testimonial',
                        'label' => 'Client Testimonial',
                        'name' => 'client_testimonial',
                        'type' => 'textarea',
                        'rows' => 4,
                    ),
                    array(
                        'key' => 'field_case_anonymous',
                        'label' => 'Anonymous',
                        'name' => 'is_anonymous',
                        'type' => 'true_false',
                        'ui' => 1,
                    ),
                    array(
                        'key' => 'field_case_date',
                        'label' => 'Date',
                        'name' => 'case_date',
                        'type' => 'date_picker',
                        'display_format' => 'm/d/Y',
                        'return_format' => 'Y-m-d',
                    ),
                ),
            ),
            array(
                'key' => 'field_awards_section',
                'label' => 'Awards & Recognitions',
                'name' => 'awards_section',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_awards',
                'label' => 'Awards & Recognitions',
                'name' => 'awards',
                'type' => 'repeater',
                'layout' => 'table',
                'button_label' => 'Add Award',
                'sub_fields' => array(
                    array(
                        'key' => 'field_award_name',
                        'label' => 'Award Name',
                        'name' => 'award_name',
                        'type' => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_award_organization',
                        'label' => 'Issuing Organization',
                        'name' => 'organization',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_award_year',
                        'label' => 'Year',
                        'name' => 'year',
                        'type' => 'number',
                    ),
                    array(
                        'key' => 'field_award_badge',
                        'label' => 'Badge Image',
                        'name' => 'badge_image',
                        'type' => 'image',
                        'return_format' => 'array',
                    ),
                ),
            ),
            array(
                'key' => 'field_hours_section',
                'label' => 'Business Hours',
                'name' => 'hours_section',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_business_hours',
                'label' => 'Business Hours',
                'name' => 'business_hours',
                'type' => 'repeater',
                'layout' => 'table',
                'button_label' => 'Add Day',
                'sub_fields' => array(
                    array(
                        'key' => 'field_hours_day',
                        'label' => 'Day',
                        'name' => 'day_name',
                        'type' => 'select',
                        'choices' => array(
                            'Monday' => 'Monday',
                            'Tuesday' => 'Tuesday',
                            'Wednesday' => 'Wednesday',
                            'Thursday' => 'Thursday',
                            'Friday' => 'Friday',
                            'Saturday' => 'Saturday',
                            'Sunday' => 'Sunday',
                        ),
                    ),
                    array(
                        'key' => 'field_hours_open',
                        'label' => 'Open Time',
                        'name' => 'open_time',
                        'type' => 'time_picker',
                        'display_format' => 'g:i a',
                        'return_format' => 'H:i',
                    ),
                    array(
                        'key' => 'field_hours_close',
                        'label' => 'Close Time',
                        'name' => 'close_time',
                        'type' => 'time_picker',
                        'display_format' => 'g:i a',
                        'return_format' => 'H:i',
                    ),
                ),
            ),
            array(
                'key' => 'field_consultation_section',
                'label' => 'Free Consultation',
                'name' => 'consultation_section',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_consultation_enabled',
                '