<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_plumbing_company_fields',
	'title' => 'Plumbing Company Fields',
	'fields' => array(
		array(
			'key' => 'field_services',
			'label' => 'Services',
			'name' => 'services',
			'type' => 'repeater',
			'instructions' => 'Add and manage plumbing services offered',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Service',
			'sub_fields' => array(
				array(
					'key' => 'field_service_name',
					'label' => 'Service Name',
					'name' => 'service_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_service_category',
					'label' => 'Category',
					'name' => 'service_category',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'residential' => 'Residential',
						'commercial' => 'Commercial',
						'emergency' => 'Emergency',
					),
					'default_value' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
				),
				array(
					'key' => 'field_service_description',
					'label' => 'Description',
					'name' => 'service_description',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_service_price_range',
					'label' => 'Typical Price Range',
					'name' => 'service_price_range',
					'type' => 'text',
					'instructions' => 'e.g., $150 - $500',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_service_duration',
					'label' => 'Estimated Duration',
					'name' => 'service_duration',
					'type' => 'text',
					'instructions' => 'e.g., 2-4 hours',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_service_image',
					'label' => 'Image',
					'name' => 'service_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '10',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array(
			'key' => 'field_service_areas',
			'label' => 'Service Areas',
			'name' => 'service_areas',
			'type' => 'repeater',
			'instructions' => 'Add cities/towns and zip codes served',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Service Area',
			'sub_fields' => array(
				array(
					'key' => 'field_area_city',
					'label' => 'City/Town',
					'name' => 'area_city',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_area_zip_codes',
					'label' => 'Zip Codes Served',
					'name' => 'area_zip_codes',
					'type' => 'text',
					'instructions' => 'Comma-separated list',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_area_same_day',
					'label' => 'Same-Day Service Available',
					'name' => 'area_same_day_available',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '35',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Yes',
					'ui_off_text' => 'No',
				),
			),
		),
		array(
			'key' => 'field_team_members',
			'label' => 'Team Members',
			'name' => 'team_members',
			'type' => 'repeater',
			'instructions' => 'Add and manage team member profiles',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Team Member',
			'sub_fields' => array(
				array(
					'key' => 'field_member_name',
					'label' => 'Name',
					'name' => 'member_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_member_role',
					'label' => 'Role',
					'name' => 'member_role',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'master_plumber' => 'Master Plumber',
						'journeyman' => 'Journeyman',
						'apprentice' => 'Apprentice',
						'office' => 'Office',
					),
					'default_value' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
				),
				array(
					'key' => 'field_member_photo',
					'label' => 'Photo',
					'name' => 'member_photo',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_member_license',
					'label' => 'License Number',
					'name' => 'member_license_number',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_member_certifications',
					'label' => 'Certifications',
					'name' => 'member_certifications',
					'type' => 'textarea',
					'instructions' => 'List certifications (one per line)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_member_years_experience',
					'label' => 'Years of Experience',
					'name' => 'member_years_experience',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '10',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => 'years',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_member_bio',
					'label' => 'Bio',
					'name' => 'member_bio',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'wpautop',
				),
			),
		),
		array(
			'key' => 'field_licenses_certifications',
			'label' => 'Licenses & Certifications',
			'name' => 'licenses_certifications',
			'type' => 'repeater',
			'instructions' => 'Company licenses and certifications',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add License/Certification',
			'sub_fields' => array(
				array(
					'key' => 'field_license_type',
					'label' => 'License Type',
					'name' => 'license_type',
					'type' => 'text',
					'instructions' => 'e.g., Plumbing License, Gas License',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_license_number',
					'label' => 'License Number',
					'name' => 'license_number',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_license_state',
					'label' => 'State',
					'name' => 'license_state',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '10',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_license_expiration',
					'label' => 'Expiration Date',
					'name' => 'license_expiration_date',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/d/Y',
					'return_format' => 'm/d/Y',
					'first_day' => 0,
				),
				array(
					'key' => 'field_license_authority',
					'label' => 'Issuing Authority',
					'name' => 'license_issuing_authority',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_business_hours',
			'label' => 'Business Hours',
			'name' => 'business_hours',
			'type' => 'repeater',
			'instructions' => 'Set business hours for each day of the week',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 7,
			'layout' => 'table',
			'button_label' => 'Add Day',
			'sub_fields' => array(
				array(
					'key' => 'field_hours_day',
					'label' => 'Day',
					'name' => 'hours_day',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'monday' => 'Monday',
						'tuesday' => 'Tuesday',
						'wednesday' => 'Wednesday',
						'thursday' => 'Thursday',
						'friday' => 'Friday',
						'saturday' => 'Saturday',
						'sunday' => 'Sunday',
					),
					'default_value' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
				),
				array(
					'key' => 'field_hours_open_time',
					'label' => 'Open Time',
					'name' => 'hours_open_time',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'g:i a',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_hours_close_time',
					'label' => 'Close Time',
					'name' => 'hours_close_time',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'g:i a',
					'return_format' => 'H:i',
				),
				array(
					'key' => 'field_hours_is_closed',
					'label' => 'Closed',
					'name' => 'hours_is_closed',
					'type' => 'true_false',
					'instructions' => 'Mark if closed this day',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Closed',
					'ui_off_text' => 'Open',
				),
			),
		),
		array(
			'key' => 'field_emergency_service',
			'label' => 'Emergency / 24-7 Service',
			'name' => 'emergency_service',
			'type' => 'group',
			'instructions' => 'Configure emergency service details',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_emergency_available',
					'label' => '24/7 Emergency Service Available',
					'name' => 'emergency_available',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Yes',
					'ui_off_text' => 'No',
				),
				array(
					'key' => 'field_emergency_phone',
					'label' => 'Emergency Phone Number',
					'name' => 'emergency_phone',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_emergency_available',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_emergency_response_time',
					'label' => 'Average Response Time',
					'name' => 'emergency_response_time',
					'type' => 'text',
					'instructions' => 'e.g., 30 minutes',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_emergency_available',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_emergency_dispatch_fee',
					'label' => 'Dispatch Fee',
					'name' => 'emergency_dispatch_fee',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_emergency_available',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '$',
					'prepend' => '$',
					'append' => '',
				),
				array(
					'key' => 'field_emergency_areas_covered',
					'label' => 'Areas Covered for Emergency Service',
					'name' => 'emergency_areas_covered',
					'type' => 'textarea',
					'instructions' => 'List areas/cities (one per line)',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_emergency_available',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'wpautop',
				),
			),
		),
		array(
			'key' => 'field_brands_products',
			'label' => 'Brands & Products',
			'name' => 'brands_products',
			'type' => 'repeater',
			'instructions' => 'Add brands and products your company uses/recommends',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Brand/Product',
			'sub_fields' => array(
				array(
					'key' => 'field_brand_name',
					'label' => 'Brand Name',
					'name' => 'brand_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_brand_logo',
					'label' => 'Logo',
					'name' => 'brand_logo',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_brand_categories',
					'label' => 'Product Categories',
					'name' => 'brand_product_categories',
					'type' => 'text',
					'instructions' => 'Comma-separated categories',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '35',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'e.g., Faucets, Toilets, Valves',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_brand_preferred',
					'label' => 'Preferred Vendor',
					'name' => 'brand_preferred_vendor',
					'type' => 'true_false',
					'instructions' => 'Mark as preferred vendor',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Yes',
					'ui_off_text' => 'No',
				),
			),
		),
		array(
			'key' => 'field_specials_coupons',
			'label' => 'Specials & Coupons',
			'name' => 'specials_coupons',
			'type' => 'repeater',
			'instructions' => 'Create promotions and coupon offers',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Offer',
			'sub_fields' => array(
				array(
					'key' => 'field_offer_title',
					'label' => 'Offer Title',
					'name' => 'offer_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_offer_code',
					'label' => 'Coupon Code',
					'name' => 'offer_code',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_offer_discount',
					'label' => 'Discount Amount',
					'name' => 'offer_discount_amount',
					'type' => 'text',
					'instructions' => 'e.g., $50 or 15%',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_offer_description',
					'label' => 'Description',
					'name' => 'offer_description',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'wpaut