<?php

acf_import_field_group(array(
    'key' => 'group_plumbing_company_fields',
    'title' => 'Plumbing Company Information',
    'fields' => array(
        array(
            'key' => 'field_services',
            'label' => 'Services',
            'name' => 'services',
            'type' => 'repeater',
            'layout' => 'table',
            'button_label' => 'Add Service',
            'sub_fields' => array(
                array(
                    'key' => 'field_service_name',
                    'label' => 'Service Name',
                    'name' => 'service_name',
                    'type' => 'text',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_service_category',
                    'label' => 'Category',
                    'name' => 'service_category',
                    'type' => 'select',
                    'choices' => array(
                        'residential' => 'Residential',
                        'commercial' => 'Commercial',
                        'emergency' => 'Emergency',
                    ),
                    'required' => 1,
                ),
                array(
                    'key' => 'field_service_description',
                    'label' => 'Description',
                    'name' => 'service_description',
                    'type' => 'textarea',
                ),
                array(
                    'key' => 'field_service_price_range',
                    'label' => 'Typical Price Range',
                    'name' => 'service_price_range',
                    'type' => 'text',
                    'placeholder' => '$100 - $500',
                ),
                array(
                    'key' => 'field_service_duration',
                    'label' => 'Estimated Duration',
                    'name' => 'service_duration',
                    'type' => 'text',
                    'placeholder' => '1-2 hours',
                ),
                array(
                    'key' => 'field_service_image',
                    'label' => 'Service Image',
                    'name' => 'service_image',
                    'type' => 'image',
                    'return_format' => 'array',
                ),
            ),
        ),
        array(
            'key' => 'field_service_areas',
            'label' => 'Service Areas',
            'name' => 'service_areas',
            'type' => 'repeater',
            'layout' => 'table',
            'button_label' => 'Add Service Area',
            'sub_fields' => array(
                array(
                    'key' => 'field_area_city',
                    'label' => 'City/Town',
                    'name' => 'area_city',
                    'type' => 'text',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_area_zip_codes',
                    'label' => 'Zip Codes Served',
                    'name' => 'area_zip_codes',
                    'type' => 'text',
                    'placeholder' => '12345, 12346, 12347',
                ),
                array(
                    'key' => 'field_area_same_day',
                    'label' => 'Same Day Service Available',
                    'name' => 'area_same_day',
                    'type' => 'true_false',
                    'ui' => 1,
                ),
            ),
        ),
        array(
            'key' => 'field_team_members',
            'label' => 'Team Members',
            'name' => 'team_members',
            'type' => 'repeater',
            'layout' => 'block',
            'button_label' => 'Add Team Member',
            'sub_fields' => array(
                array(
                    'key' => 'field_member_name',
                    'label' => 'Name',
                    'name' => 'member_name',
                    'type' => 'text',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_member_role',
                    'label' => 'Role',
                    'name' => 'member_role',
                    'type' => 'select',
                    'choices' => array(
                        'master_plumber' => 'Master Plumber',
                        'journeyman' => 'Journeyman',
                        'apprentice' => 'Apprentice',
                        'office' => 'Office Staff',
                    ),
                    'required' => 1,
                ),
                array(
                    'key' => 'field_member_photo',
                    'label' => 'Photo',
                    'name' => 'member_photo',
                    'type' => 'image',
                    'return_format' => 'array',
                ),
                array(
                    'key' => 'field_member_license',
                    'label' => 'License Number',
                    'name' => 'member_license',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_member_certifications',
                    'label' => 'Certifications',
                    'name' => 'member_certifications',
                    'type' => 'textarea',
                    'placeholder' => 'List certifications separated by commas',
                ),
                array(
                    'key' => 'field_member_experience',
                    'label' => 'Years of Experience',
                    'name' => 'member_experience',
                    'type' => 'number',
                ),
                array(
                    'key' => 'field_member_bio',
                    'label' => 'Bio',
                    'name' => 'member_bio',
                    'type' => 'textarea',
                ),
            ),
        ),
        array(
            'key' => 'field_licenses_certifications',
            'label' => 'Licenses & Certifications',
            'name' => 'licenses_certifications',
            'type' => 'repeater',
            'layout' => 'table',
            'button_label' => 'Add License/Certification',
            'sub_fields' => array(
                array(
                    'key' => 'field_license_type',
                    'label' => 'License Type',
                    'name' => 'license_type',
                    'type' => 'text',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_license_number',
                    'label' => 'License Number',
                    'name' => 'license_number',
                    'type' => 'text',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_license_state',
                    'label' => 'State',
                    'name' => 'license_state',
                    'type' => 'select',
                    'choices' => array(
                        'AL' => 'Alabama',
                        'AK' => 'Alaska',
                        'AZ' => 'Arizona',
                        'AR' => 'Arkansas',
                        'CA' => 'California',
                        'CO' => 'Colorado',
                        'CT' => 'Connecticut',
                        'DE' => 'Delaware',
                        'FL' => 'Florida',
                        'GA' => 'Georgia',
                        'HI' => 'Hawaii',
                        'ID' => 'Idaho',
                        'IL' => 'Illinois',
                        'IN' => 'Indiana',
                        'IA' => 'Iowa',
                        'KS' => 'Kansas',
                        'KY' => 'Kentucky',
                        'LA' => 'Louisiana',
                        'ME' => 'Maine',
                        'MD' => 'Maryland',
                        'MA' => 'Massachusetts',
                        'MI' => 'Michigan',
                        'MN' => 'Minnesota',
                        'MS' => 'Mississippi',
                        'MO' => 'Missouri',
                        'MT' => 'Montana',
                        'NE' => 'Nebraska',
                        'NV' => 'Nevada',
                        'NH' => 'New Hampshire',
                        'NJ' => 'New Jersey',
                        'NM' => 'New Mexico',
                        'NY' => 'New York',
                        'NC' => 'North Carolina',
                        'ND' => 'North Dakota',
                        'OH' => 'Ohio',
                        'OK' => 'Oklahoma',
                        'OR' => 'Oregon',
                        'PA' => 'Pennsylvania',
                        'RI' => 'Rhode Island',
                        'SC' => 'South Carolina',
                        'SD' => 'South Dakota',
                        'TN' => 'Tennessee',
                        'TX' => 'Texas',
                        'UT' => 'Utah',
                        'VT' => 'Vermont',
                        'VA' => 'Virginia',
                        'WA' => 'Washington',
                        'WV' => 'West Virginia',
                        'WI' => 'Wisconsin',
                        'WY' => 'Wyoming',
                    ),
                    'required' => 1,
                ),
                array(
                    'key' => 'field_license_expiration',
                    'label' => 'Expiration Date',
                    'name' => 'license_expiration',
                    'type' => 'date_picker',
                    'display_format' => 'm/d/Y',
                    'return_format' => 'Y-m-d',
                ),
                array(
                    'key' => 'field_license_authority',
                    'label' => 'Issuing Authority',
                    'name' => 'license_authority',
                    'type' => 'text',
                ),
            ),
        ),
        array(
            'key' => 'field_business_hours',
            'label' => 'Business Hours',
            'name' => 'business_hours',
            'type' => 'repeater',
            'layout' => 'table',
            'button_label' => 'Add Day',
            'sub_fields' => array(
                array(
                    'key' => 'field_hours_day',
                    'label' => 'Day',
                    'name' => 'hours_day',
                    'type' => 'select',
                    'choices' => array(
                        'monday' => 'Monday',
                        'tuesday' => 'Tuesday',
                        'wednesday' => 'Wednesday',
                        'thursday' => 'Thursday',
                        'friday' => 'Friday',
                        'saturday' => 'Saturday',
                        'sunday' => 'Sunday',
                    ),
                    'required' => 1,
                ),
                array(
                    'key' => 'field_hours_open',
                    'label' => 'Open Time',
                    'name' => 'hours_open',
                    'type' => 'time_picker',
                    'display_format' => 'g:i a',
                    'return_format' => 'H:i',
                ),
                array(
                    'key' => 'field_hours_close',
                    'label' => 'Close Time',
                    'name' => 'hours_close',
                    'type' => 'time_picker',
                    'display_format' => 'g:i a',
                    'return_format' => 'H:i',
                ),
                array(
                    'key' => 'field_hours_closed',
                    'label' => 'Closed',
                    'name' => 'hours_closed',
                    'type' => 'true_false',
                    'ui' => 1,
                ),
            ),
        ),
        array(
            'key' => 'field_emergency_service',
            'label' => '24/7 Emergency Service',
            'name' => 'emergency_service',
            'type' => 'true_false',
            'ui' => 1,
        ),
        array(
            'key' => 'field_emergency_phone',
            'label' => 'Emergency Phone Number',
            'name' => 'emergency_phone',
            'type' => 'text',
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_emergency_service',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_emergency_response_time',
            'label' => 'Average Response Time',
            'name' => 'emergency_response_time',
            'type' => 'text',
            'placeholder' => '30 minutes',
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_emergency_service',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_emergency_dispatch_fee',
            'label' => 'Emergency Dispatch Fee',
            'name' => 'emergency_dispatch_fee',
            'type' => 'text',
            'placeholder' => '$75',
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_emergency_service',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_emergency_areas',
            'label' => 'Emergency Service Areas',
            'name' => 'emergency_areas',
            'type' => 'textarea',
            'placeholder' => 'List the areas covered for emergency service',
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_emergency_service',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_brands_products',
            'label' => 'Brands & Products',
            'name' => 'brands_products',
            'type' => 'repeater',
            'layout' => 'block',
            'button_label' => 'Add Brand',
            'sub_fields' => array(
                array(
                    'key' => 'field_brand_name',
                    'label' => 'Brand Name',
                    'name' => 'brand_name',
                    'type' => 'text',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_brand_logo',
                    'label' => 'Brand Logo',
                    'name' => 'brand_logo',
                    'type' => 'image',
                    'return_format' => 'array',
                ),
                array(
                    'key' => 'field_brand_categories',
                    'label' => 'Product Categories',
                    'name' => 'brand_categories',
                    'type' => 'textarea',
                    'placeholder' => 'List product categories separated by commas',
                ),
                array(
                    'key' => 'field_brand_preferred',
                    'label' => 'Preferred Vendor',
                    'name' => 'brand_preferred',
                    'type' => 'true_false',
                    'ui' => 1,
                ),
            ),
        ),
        array(
            'key' => 'field_specials_coupons',
            'label' =>