<?php

acf_import_field_group(array(
	'key' => 'group_roofing_contractor_fields',
	'title' => 'Roofing Contractor Information',
	'fields' => array(
		array(
			'key' => 'field_services_section',
			'label' => 'Services',
			'name' => 'services',
			'type' => 'repeater',
			'instructions' => 'Add and manage roofing services offered',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Service',
			'sub_fields' => array(
				array(
					'key' => 'field_service_name',
					'label' => 'Service Name',
					'name' => 'service_name',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'roof_repair' => 'Roof Repair',
						'roof_replacement' => 'Roof Replacement',
						'roof_inspection' => 'Roof Inspection',
						'gutter_installation' => 'Gutter Installation',
						'gutter_cleaning' => 'Gutter Cleaning',
						'siding' => 'Siding',
						'fascia_soffit' => 'Fascia & Soffit',
						'skylight_installation' => 'Skylight Installation',
						'roof_coating' => 'Roof Coating',
						'leak_detection' => 'Leak Detection',
					),
					'default_value' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'return_format' => 'value',
					'ajax' => 0,
				),
				array(
					'key' => 'field_service_description',
					'label' => 'Description',
					'name' => 'description',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_service_type',
					'label' => 'Service Type',
					'name' => 'service_type',
					'type' => 'select',
					'instructions' => 'Is this service for residential or commercial?',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'residential' => 'Residential',
						'commercial' => 'Commercial',
						'both' => 'Both Residential & Commercial',
					),
					'default_value' => 'both',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
				),
				array(
					'key' => 'field_service_image',
					'label' => 'Service Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array(
			'key' => 'field_roofing_materials_section',
			'label' => 'Roofing Materials',
			'name' => 'roofing_materials',
			'type' => 'repeater',
			'instructions' => 'Add and manage roofing material options',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Material',
			'sub_fields' => array(
				array(
					'key' => 'field_material_name',
					'label' => 'Material Name',
					'name' => 'material_name',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'asphalt_shingles' => 'Asphalt Shingles',
						'metal_roofing' => 'Metal Roofing',
						'clay_tile' => 'Clay Tile',
						'concrete_tile' => 'Concrete Tile',
						'slate' => 'Slate',
						'flat_roof' => 'Flat Roof / EPDM',
						'tpo' => 'TPO',
						'pvc' => 'PVC',
						'wood_shakes' => 'Wood Shakes',
						'rubber_roofing' => 'Rubber Roofing',
					),
					'default_value' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'return_format' => 'value',
					'ajax' => 0,
				),
				array(
					'key' => 'field_material_description',
					'label' => 'Description',
					'name' => 'description',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_material_warranty',
					'label' => 'Warranty (Years)',
					'name' => 'warranty_years',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '10',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => 'years',
					'min' => 0,
					'max' => '',
					'step' => 1,
				),
				array(
					'key' => 'field_material_pros',
					'label' => 'Pros',
					'name' => 'pros',
					'type' => 'textarea',
					'instructions' => 'List key advantages',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_material_cons',
					'label' => 'Cons',
					'name' => 'cons',
					'type' => 'textarea',
					'instructions' => 'List key disadvantages',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_material_image',
					'label' => 'Material Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array(
			'key' => 'field_service_areas_section',
			'label' => 'Service Areas',
			'name' => 'service_areas',
			'type' => 'repeater',
			'instructions' => 'Define service areas and coverage zones',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Service Area',
			'sub_fields' => array(
				array(
					'key' => 'field_area_name',
					'label' => 'City / County Name',
					'name' => 'area_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'e.g., Denver Metro Area',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_area_zip_codes',
					'label' => 'Zip Codes',
					'name' => 'zip_codes',
					'type' => 'textarea',
					'instructions' => 'Enter zip codes separated by commas',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '35',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '80202, 80203, 80204',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => '',
				),
				array(
					'key' => 'field_area_travel_fee',
					'label' => 'Travel Fee',
					'name' => 'travel_fee',
					'type' => 'number',
					'instructions' => 'Leave blank for no charge',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '0',
					'prepend' => '$',
					'append' => '',
					'min' => 0,
					'max' => '',
					'step' => 0.01,
				),
				array(
					'key' => 'field_area_available',
					'label' => 'Available',
					'name' => 'available',
					'type' => 'true_false',
					'instructions' => 'Is this service area currently accepting new customers?',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'message' => 'Yes, accepting new customers',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Yes',
					'ui_off_text' => 'No',
				),
			),
		),
		array(
			'key' => 'field_team_info_section',
			'label' => 'Team / Crew Information',
			'name' => 'team_info',
			'type' => 'repeater',
			'instructions' => 'Add team members and crew details',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_team_name',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Team Member',
			'sub_fields' => array(
				array(
					'key' => 'field_team_name',
					'label' => 'Name',
					'name' => 'name',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_team_role',
					'label' => 'Role / Position',
					'name' => 'role',
					'type' => 'text',
					'instructions' => 'e.g., Lead Roofer, Crew Chief, Estimator',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_team_years_experience',
					'label' => 'Years of Experience',
					'name' => 'years_experience',
					'type' => 'number',
					'instructions' => '',
					'