<?php

acf_import_field_group(array(
    'key' => 'group_roofing_contractor_fields',
    'title' => 'Roofing Contractor Fields',
    'fields' => array(
        array(
            'key' => 'field_services',
            'label' => 'Services',
            'name' => 'services',
            'type' => 'repeater',
            'instructions' => 'Add roofing services offered',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add Service',
            'sub_fields' => array(
                array(
                    'key' => 'field_service_name',
                    'label' => 'Service Name',
                    'name' => 'service_name',
                    'type' => 'select',
                    'choices' => array(
                        'roof_repair' => 'Roof Repair',
                        'roof_replacement' => 'Roof Replacement',
                        'inspection' => 'Roof Inspection',
                        'gutter_service' => 'Gutter Service',
                        'siding' => 'Siding',
                        'snow_removal' => 'Snow Removal',
                        'moss_cleaning' => 'Moss Cleaning',
                        'fascia_soffit' => 'Fascia & Soffit',
                        'skylight' => 'Skylight Installation',
                        'ventilation' => 'Ventilation',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                ),
                array(
                    'key' => 'field_service_description',
                    'label' => 'Description',
                    'name' => 'description',
                    'type' => 'textarea',
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_service_type',
                    'label' => 'Type',
                    'name' => 'residential_or_commercial',
                    'type' => 'select',
                    'choices' => array(
                        'residential' => 'Residential',
                        'commercial' => 'Commercial',
                        'both' => 'Both',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_service_image',
                    'label' => 'Service Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
            ),
        ),
        array(
            'key' => 'field_roofing_materials',
            'label' => 'Roofing Materials',
            'name' => 'roofing_materials',
            'type' => 'repeater',
            'instructions' => 'Add roofing materials available',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add Material',
            'sub_fields' => array(
                array(
                    'key' => 'field_material_name',
                    'label' => 'Material Name',
                    'name' => 'material_name',
                    'type' => 'select',
                    'choices' => array(
                        'asphalt_shingles' => 'Asphalt Shingles',
                        'metal' => 'Metal Roofing',
                        'tile' => 'Tile',
                        'slate' => 'Slate',
                        'flat_roof' => 'Flat Roof (TPO/EPDM)',
                        'wood_shake' => 'Wood Shake',
                        'composite' => 'Composite',
                        'living_green' => 'Living/Green Roof',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_material_description',
                    'label' => 'Description',
                    'name' => 'description',
                    'type' => 'textarea',
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_warranty_years',
                    'label' => 'Warranty (Years)',
                    'name' => 'warranty_years',
                    'type' => 'number',
                    'min' => 1,
                    'max' => 100,
                ),
                array(
                    'key' => 'field_material_pros',
                    'label' => 'Pros',
                    'name' => 'pros',
                    'type' => 'textarea',
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_material_cons',
                    'label' => 'Cons',
                    'name' => 'cons',
                    'type' => 'textarea',
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_material_image',
                    'label' => 'Material Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
            ),
        ),
        array(
            'key' => 'field_service_areas',
            'label' => 'Service Areas',
            'name' => 'service_areas',
            'type' => 'repeater',
            'instructions' => 'Add cities, counties, and service areas',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add Service Area',
            'sub_fields' => array(
                array(
                    'key' => 'field_area_name',
                    'label' => 'City/County Name',
                    'name' => 'area_name',
                    'type' => 'text',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_area_zip_codes',
                    'label' => 'Zip Codes',
                    'name' => 'zip_codes',
                    'type' => 'text',
                    'instructions' => 'Comma separated',
                ),
                array(
                    'key' => 'field_area_travel_fee',
                    'label' => 'Travel Fee',
                    'name' => 'travel_fee',
                    'type' => 'number',
                    'step' => 0.01,
                ),
            ),
        ),
        array(
            'key' => 'field_team_crew',
            'label' => 'Team / Crew',
            'name' => 'team_crew',
            'type' => 'repeater',
            'instructions' => 'Add team members and crew information',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add Team Member',
            'sub_fields' => array(
                array(
                    'key' => 'field_team_name',
                    'label' => 'Name',
                    'name' => 'name',
                    'type' => 'text',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_team_role',
                    'label' => 'Role',
                    'name' => 'role',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_team_photo',
                    'label' => 'Photo',
                    'name' => 'photo',
                    'type' => 'image',
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_team_certifications',
                    'label' => 'Certifications',
                    'name' => 'certifications',
                    'type' => 'textarea',
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_team_experience',
                    'label' => 'Years Experience',
                    'name' => 'years_experience',
                    'type' => 'number',
                    'min' => 0,
                    'max' => 100,
                ),
            ),
        ),
        array(
            'key' => 'field_certifications',
            'label' => 'Certifications & Manufacturer Partnerships',
            'name' => 'certifications',
            'type' => 'repeater',
            'instructions' => 'Add certifications and manufacturer partnerships',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add Certification',
            'sub_fields' => array(
                array(
                    'key' => 'field_cert_name',
                    'label' => 'Certification Name',
                    'name' => 'cert_name',
                    'type' => 'text',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_cert_manufacturer',
                    'label' => 'Manufacturer',
                    'name' => 'manufacturer',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_cert_level',
                    'label' => 'Certification Level',
                    'name' => 'cert_level',
                    'type' => 'select',
                    'choices' => array(
                        'preferred' => 'Preferred',
                        'elite' => 'Elite',
                        'master' => 'Master',
                        'standard' => 'Standard',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_cert_image',
                    'label' => 'Certificate Image',
                    'name' => 'cert_image',
                    'type' => 'image',
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_cert_number',
                    'label' => 'Certification Number',
                    'name' => 'cert_number',
                    'type' => 'text',
                ),
            ),
        ),
        array(
            'key' => 'field_project_gallery',
            'label' => 'Project Gallery',
            'name' => 'project_gallery',
            'type' => 'repeater',
            'instructions' => 'Add completed projects to gallery',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add Project',
            'sub_fields' => array(
                array(
                    'key' => 'field_project_title',
                    'label' => 'Project Title',
                    'name' => 'project_title',
                    'type' => 'text',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_project_before_photo',
                    'label' => 'Before Photo',
                    'name' => 'before_photo',
                    'type' => 'image',
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_project_after_photo',
                    'label' => 'After Photo',
                    'name' => 'after_photo',
                    'type' => 'image',
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_project_roof_type',
                    'label' => 'Roof Type',
                    'name' => 'roof_type',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_project_description',
                    'label' => 'Description',
                    'name' => 'description',
                    'type' => 'textarea',
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_project_city',
                    'label' => 'City',
                    'name' => 'city',
                    'type' => 'text',
                ),
            ),
        ),
        array(
            'key' => 'field_warranties',
            'label' => 'Warranty Information',
            'name' => 'warranties',
            'type' => 'repeater',
            'instructions' => 'Add warranty information',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add Warranty',
            'sub_fields' => array(
                array(
                    'key' => 'field_warranty_type',
                    'label' => 'Warranty Type',
                    'name' => 'warranty_type',
                    'type' => 'select',
                    'choices' => array(
                        'workmanship' => 'Workmanship',
                        'material' => 'Material',
                        'extended' => 'Extended',
                        'transferable' => 'Transferable',
                        'manufacturer' => 'Manufacturer',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_warranty_coverage',
                    'label' => 'Coverage Description',
                    'name' => 'coverage_description',
                    'type' => 'textarea',
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_warranty_duration',
                    'label' => 'Duration (Years)',
                    'name' => 'duration_years',
                    'type' => 'number',
                    'min' => 1,
                    'max' => 100,
                ),
                array(
                    'key' => 'field_warranty_terms',
                    'label' => 'Terms & Conditions',
                    'name' => 'terms',
                    'type' => 'textarea',
                    'rows' => 3,
                ),
            ),
        ),
        array(
            'key' => 'field_insurance_bonding',
            'label' => 'Insurance & Bonding',
            'name' => 'insurance_bonding',
            'type' => 'group',
            'instructions' => 'Add insurance and bonding information',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_license_number',
                    'label' => 'License Number',
                    'name' => 'license_number',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_insurance_carrier',
                    'label' => 'Insurance Carrier',
                    'name' => 'insurance_carrier',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_bond_amount',
                    'label' => 'Bond Amount',
                    'name' => 'bond_amount',
                    'type' => 'number',
                    'step' => 0.01,
                ),
                array(
                    'key' => 'field_insurance_cert',
                    'label' => 'Insurance Certificate',
                    'name' => 'insurance_cert',
                    'type' => 'file',
                    'return_format' => 'array',
                ),
            ),
        ),
        array(
            'key' => 'field_storm_emergency',
            'label' => 'Storm Damage & Emergency Service',
            'name' => 'storm_emergency',
            'type' => 'group',
            'instructions' => 'Configure storm damage and emergency services',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_storm_service_enabled',
                    'label' => 'Offer Storm Damage Service',
                    'name' => 'storm_service_enabled',
                    'type' => 'true_false',
                    'message' => 'Enable emergency storm damage response',
                    'ui' => 1,
                    'ui_on_text' => 'Yes',
                    'ui_off_text' => 'No',
                ),
                array(
                    'key' => 'field_response_time',
                    'label' => 'Response Time',
                    'name' => 'response_time',
                    'type' => 'text',
                    'instructions' => 'e.g., "24 hours" or "Same day"',
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_storm_service_enabled',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                ),
                array(
                    'key' => 'field_storm_types',
                    'label' => 'Storm Types Handled',
                    'name' => 'storm_types',
                    'type' => 'repeater',
                    'instructions' => 'Add types of storms handled',
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_storm_service_enabled',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'Add Storm Type',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_storm_type_name',
                            'label' => 'Storm Type',
                            'name' => 'storm_type',
                            'type' => 'select',
                            'choices' => array(
                                'hail' => 'Hail',
                                'wind' => 'Wind',
                                'tornado' => 'Tornado',
                                'hurricane' => 'Hurricane',
                                'heavy_rain' => 'Heavy Rain',
                                'snow_ice' => 'Snow/Ice',
                                'lightning' => 'Lightning',
                                'tree_damage' => 'Tree Damage',
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_insurance_claim_assist',
                    'label' => 'Assist with Insurance Claims',
                    'name' => 'insurance_claim_assistance',
                    'type' => 'true_false',
                    'message' => 'Offer insurance claim assistance',
                    'ui' => 1,
                    'ui_on_text' => 'Yes',
                    'ui_off_text' => 'No',
                ),
            ),
        ),
        array(
            'key' => 'field_financing',
            'label' => 'Financing Options',
            'name' => 'financing',
            'type' => 'repeater',
            'instructions' => 'Add financing and payment plan options',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add Financing Option',
            'sub_fields' => array(
                array(
                    'key' => 'field_financing_lender',
                    'label' => 'Lender Name',
                    'name' => 'lender_name',
                    'type' => 'text',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_financing_terms',
                    'label' => 'Terms',
                    'name' => 'terms',
                    'type' => 'text',
                    'instructions' => 'e.g., "No interest for 12 months"',
                ),
                array(
                    'key' => 'field_financing_min_credit',
                    'label' => 'Minimum Credit Score',
                    'name' => 'minimum_credit_score',
                    'type' => 'number',
                    'min' => 300,
                    'max' => 850,
                ),
                array(
                    'key' => 'field_financing_apply_url',
                    'label' => 'Apply URL',
                    'name' => 'apply_url',
                    'type' => 'url',
                ),
            ),
        ),
        array(
            'key' => 'field_business_hours',
            'label' => 'Business Hours & Availability',
            'name' => 'business_hours',
            'type' => 'group',
            'instructions' => 'Configure business hours and seasonal notes',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_monday_hours',
                    'label' => 'Monday Hours',
                    'name' => 'monday_hours',
                    'type' => 'text',
                    'placeholder' => '8:00 AM - 5:00 PM',
                ),
                array(
                    'key' => 'field_tuesday_hours',
                    'label' => 'Tuesday Hours',
                    'name' => 'tuesday_hours',
                    'type' => 'text',
                    'placeholder' => '8:00 AM - 5:00 PM',
                ),
                array(
                    'key' => 'field_wednesday_hours',
                    'label' => 'Wednesday Hours',
                    'name' => 'wednesday_hours',
                    'type' => 'text',
                    'placeholder' => '8:00 AM - 5:00 PM',
                ),
                array(
                    'key' => 'field_thursday_hours',
                    'label' => 'Thursday Hours',
                    'name' => 'thursday_hours',
                    'type' => 'text',
                    'placeholder' => '8:00 AM - 5:00 PM',
                ),
                array(
                    'key' => 'field_friday_hours',
                    'label' => 'Friday Hours',
                    'name' => 'friday_hours',
                    'type' => 'text',
                    'placeholder' => '8:00 AM - 5:00 PM',
                ),
                array(
                    'key' => 'field_saturday_hours',
                    'label' => 'Saturday Hours',
                    'name' => 'saturday_hours',
                    'type' => 'text',
                    'placeholder' => 'Closed',
                ),
                array(
                    'key' => 'field_sunday_hours',
                    'label' => 'Sunday Hours',
                    'name' => 'sunday_hours',
                    'type' => 'text',
                    'placeholder' => 'Closed',
                ),
                array(
                    'key' => 'field_seasonal_notes',
                    'label' => 'Seasonal Availability Notes',
                    'name' => 'seasonal_notes',
                    'type' => 'textarea',
                    'rows' => 4,
                    'instructions' => 'Note any seasonal closures or busy periods',
                ),
                array(
                    'key' => 'field_emergency_contact',
                    'label' => 'Emergency Contact Number',
                    'name' => 'emergency_contact',
                    'type' => 'text',
                    'placeholder' => '(555) 123-4567',
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'page',
            ),
            array(
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'default',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Complete field group for roofing contractor website information',
));